config/routes.rb
Rails.application.routes.draw do
  resources :products, except: :show

  resources :units, only: :destroy

  root "products#index"
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :units

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :units, dependent: :destroy

  accepts_nested_attributes_for :units

  validates :name, presence: true
end

app/models/size.rb
class Size < ActiveRecord::Base
  has_many :units

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :product
  belongs_to :color
  belongs_to :size

  validates :color, :size, presence: true

  validates :quantity, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @product.units.build
  end

  def create
    @product = Product.new(product_params)

    if @product.save!
      redirect_to products_path, notice: 'Produto cadastrado com sucesso!'
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to products_path, notice: 'Produto atualizado com sucesso!'
    else
      render :new
    end
  end

  def destroy
    Product.find(params[:id]).destroy

    redirect_to products_path, notice: 'Unidade removida com sucesso'
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, units_attributes: [:id, :color_id, :size_id, :quantity])
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def destroy
    Unit.find(params[:id]).destroy!

    redirect_to products_path, notice: 'Unidade removida com sucesso'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste Synergia Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="pt-5">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Gerenciador de estoque</a>
    </div>
  </nav>

<div class="container pt-4">

  <% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

    <%= notice %>
  </div>
  <% end %>


  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product,
  wrapper: :horizontal_form,
  wrapper_mappings: {
    boolean:       :horizontal_boolean,
    check_boxes:   :horizontal_collection,
    date:          :horizontal_multi_select,
    datetime:      :horizontal_multi_select,
    file:          :horizontal_file,
    radio_buttons: :horizontal_collection,
    range:         :horizontal_range,
    time:          :horizontal_multi_select
  } do |f| %>

  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :description %>

  <h5 class="border-bottom border-primary">Unidades</h5>

  <table class="table table-units">
    <thead>
    <tr>
      <td>Cor</td>
      <td>Tamanho</td>
      <td>Quantidade</td>
      <td style="width: 1px"><a href="#" class="btn btn-primary btn-sm unit-add">Adicionar</a></td>
    </tr>
    </thead>
    <tbody>
    <%= f.simple_fields_for :units, @product.units do |u| %>
    <tr>
      <td><%= u.association :color, wrapper: false, label: false %></td>
      <td><%= u.association :size, wrapper: false, label: false %></td>
      <td><%= u.input :quantity, wrapper: false, label: false, input_html:{ min: 0 } %></td>
      <td>
        <%= u.input :id, as: :hidden %>
        <a href="#" class="btn btn-danger unit-delete">Excluir</a>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>

  <hr class="border-top border-primary px-3">
  <div class="offset-sm-3 pl-2">
      <%= f.button :submit, class: 'btn-primary' %>
      <%= link_to 'Voltar', products_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h4 class="border-bottom border-primary">Edição de produto</h4>

<%= render 'form' %>

app/views/products/index.html.erb
<h4 class="border-bottom border-primary mb-4 pb-2">
  Produtos
  <%= link_to 'Novo produto', new_product_path, class: 'btn btn-primary btn-sm float-right' %>
</h4>

<% if @products.size.zero? %>
<p>Nenhum produto encontrado</p>
<% else %>
<table class="table">
  <% @products.each do |p| %>
  <thead>
    <tr>
      <th colspan="3" class="border-bottom-0">
        <%= p.name %>
        <small><%= p.description %></small>
      </th>
      <td style="width: 1px; white-space: nowrap">
        <%= link_to 'Editar', edit_product_path(p), class: 'btn btn-sm btn-primary' %>
        <%= link_to 'Excluir', product_path(p), class: 'btn btn-sm btn-danger', method: :delete %>
      </td>
    </tr>
  </thead>

  <% p.units.each do |u| %>
  <tbody>
    <tr>
      <td><%= u.color %></td>
      <td><%= u.size %></td>
      <td><%= u.quantity %></td>
      <td class="text-right">
        <%= link_to 'Excluir', unit_path(u), method: :delete, class: 'text-danger mr-2' unless p.units.one? %>
      </td>
    </tr>
  </tbody>
  <% end %>
  <% end %>
</table>
<% end %>

app/views/products/new.html.erb
<h4 class="border-bottom border-primary">Criação de novo produto</h4>

<%= simple_form_for @product,
  wrapper: :horizontal_form,
  wrapper_mappings: {
    boolean:       :horizontal_boolean,
    check_boxes:   :horizontal_collection,
    date:          :horizontal_multi_select,
    datetime:      :horizontal_multi_select,
    file:          :horizontal_file,
    radio_buttons: :horizontal_collection,
    range:         :horizontal_range,
    time:          :horizontal_multi_select
  } do |f| %>

  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :description %>

  <h5 class="border-bottom border-primary">Unidades</h5>

  <table class="table table-units">
    <thead>
    <tr>
      <td>Cor</td>
      <td>Tamanho</td>
      <td>Quantidade</td>
      <td style="width: 1px"><a href="#" class="btn btn-primary btn-sm unit-add">Adicionar</a></td>
    </tr>
    </thead>
    <tbody>
    <%= f.simple_fields_for :units do |u| %>
    <tr>
      <td><%= u.association :color, wrapper: false, label: false %></td>
      <td><%= u.association :size, wrapper: false, label: false %></td>
      <td><%= u.input :quantity, wrapper: false, label: false, input_html:{ min: 0 } %></td>
      <td><a href="#" class="btn btn-danger unit-delete">Excluir</a></td>
    </tr>
    <% end %>
    </tbody>
  </table>

  <hr class="border-top border-primary px-3">
  <div class="offset-sm-3 pl-2">
      <%= f.button :submit, class: 'btn-primary' %>
      <%= link_to 'Voltar', products_path, class: 'btn btn-default' %>
  </div>
<% end %>